apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot-svc
spec:
  selector:
    app: k8s-springboot
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # 指定 NodePort
  type: NodePort